### ISSUE TITLE
tracking: Skyra.Moderation service

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#1535]
The Moderation module is a fundamental part of Skyra as the biggest one, however, it has suffered multiple scalability issues that are otherwise fixable with C++.

This service would handle settings (via EFCore) and will have an internal connection to the bot with gRPC. This also receives the useful data from every guild message (**Message Handler**) and the useful data from every reaction in a guild message (**Reaction Handler**). Furthermore, it'll handle command running with an `op` identifying the name of the command to run (e.g. `Mute` or `Ban`) and the data.

### Progress

- [ ] Creating Moderation framework.
  - [ ] Auto Moderation 
    - [ ] Message Handler.
    - [ ] Reaction Handler.
  - [ ] Text Command Handler.
  - [ ] Slash Command Handler.
- [ ] Creating internal API.
