### ISSUE TITLE
tracking: Skyra.Cdn service

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#1536]
For very long, we have hosted all our assets in GitHub, that needs to stop:

https://github.com/skyra-project/skyra/tree/c534683db06c8ff4d6d9acd19f3509a759226e17/assets/public/skyra-assets

The new service would be written using .NET 5 and ASP.NET for very high performance, and must connect to a database. Furthermore, this service **should** strictly follow [RFC 7232](https://tools.ietf.org/html/rfc7232) (regarding **Conditional Requests**) to improve and minimise bandwidth usage.

### Progress

- [ ] Creating CDN framework.
- [ ] Creating internal API with gRPC to upload/edit files.
- [ ] Creating external API with ASP.NET to download files.
