### ISSUE TITLE
tracking: Skyra.Database service

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#1566]
The database module is the most critical component in Skyra, and we want to move it to .NET and EFCore due to the high amount of issues that arise from many different npm packages.

### Progress

- [x] Member
  - ###### Points
  - [x] `GetPoints({ UserID, GuildID }): { Experience }`
  - [x] `AddPoints({ UserID, GuildID, Points }): { Experience }`
  - [x] `RemovePoints({ UserID, GuildID, Points }): { Experience }`
  - [x] `SetPoints({ UserID, GuildID, Points }): {}`
  - [x] `ResetPoints({ UserID, GuildID }): {}`

---
- [x] User
  - ###### Points
  - [x] `GetPoints({ UserID }): { Experience }`
  - [x] `AddPoints({ UserID, Points }): { Experience }`
  - [x] `ResetPoints({ UserID }): {}`
  - ###### Money
  - [x] `AddMoney({ UserID, Money }): { Money }`
  - [x] `RemoveMoney({ UserID, Money }): { Money }`
  - [x] `SetMoney({ UserID, Money }): {}`
  - [x] `GiveMoney({ UserID, TargetID, Money }): { AuthorMoney, TargetMoney }`
  - ###### Claim
  - [x] `ClaimDaily({ UserID, Force }): { Remaining }`
    - **Note**: It updates `UserCooldown.Daily`.
    - **Note**: `Force` runs the command if Remaining is less than 1 hour. Otherwise, it should return `Success = false`.
  - ###### Reputation
  - [x] `GiveReputation({ UserID, TargetID }): {}`
    - **Note**: It updates `UserCooldown.Reputation`.
  - ###### Banners (Profile)
  - [x] `GetLargeBanners({ UserID }): { string[] }`
  - [x] `SetLargeBanner({ UserID }): {}`
  - [x] `GetAllLargeBanners({ UserID }): { string[] }`
  - ###### Banners (Level)
  - [x] `GetSmallBanners({ UserID }): { string[] }`
  - [x] `SetSmallBanner({ UserID }): {}`
  - [x] `GetAllSmallBanners({ UserID }): { string[] }`
  - ###### Badges
  - [x] `GetBadges({ UserID }): { Badges }`
  - [x] `GetAllBadges({ UserID }): { Badges }`
  - ###### Profile
  - [x] `GetColor({ UserID }): { Color }`
  - [x] `GetProfile({ UserID }): { Experience, Color, Reputation, Money, Vault, Badges, BannerProfile }`
  - ###### Spouses
  - [x] `GetSpouses({ UserID }): UserID[]`
  - [x] `AddSpouse({ UserID, TargetID }): {}`
  - [x] `RemoveSpouse({ UserID, TargetID }): {}`
  - ###### Game Integration
  - [x] `GetGameIntegration({ UserID, Game }): { JSON? }`
  - [x] `AddGameIntegration({ UserID, Game, JSON }): {}`
  - [x] `RemoveGameIntegration({ UserID, Game }): { JSON? }`
  - ###### Account Management
  - [x] `Remove({ UserID }): {}`
    - **Note**: Deletes the `User`, `UserCooldown`, and `UserProfile` entries if existing.
    - **Note**: This will come handy for removing all data from a deleted user, in accordance to GDPR.
    - Also useful for nuking data before unit tests.

---
- [x] Social
  - ###### Banners
  - [x] `GetBanners(): Banner[]`
  - [x] `AddBanner(Banner): {}`
  - [x] `UpdateBanner(Banner): {}`
  - [x] `RemoveBanner(BannerID): {}`
  - ###### Leaderboard
  - [x] `GetLocalLeaderboard({ GuildID }): UserID[]`
  - [x] `GetGlobalLeaderboard(): UserID[]`

---
- [x] Guild
  - [x] `Get({ GuildID }): { ... }`
  - [x] `Update({ GuildID, JSON }): JSON`
    - **Note**: Takes a partial JSON object with the properties to update.
    - **Note**: Returns the patched data.
  - [x] `Remove({ GuildID }): {}`

---
- [x] Starboard
  - [x] `AddMessage(StarboardData): { StarMessageID?, Count }`
  - [x] `RemoveMessage({ MessageID, ChannelID }): { StarMessageID? }`
  - [x] `RemoveMessages({ MessageID[], ChannelID }): { StarMessageID[] }`
  - [x] `RemoveChannel({ ChannelID }): { StarMessageID[] }`

---
- [x] Schedule
  - [x] `Add(TaskData): {}`
  - [x] `GetAll(): TaskData[]`
  - [x] `Update(TaskData[]): {}`
  - [x] `Remove(TaskID[]): {}`
  - [x] `RemoveAll(): {}`

---
- [x] Giveaway
  - [x] `Add(GiveawayData): {}`
  - [x] `GetAll(): GiveawayData[]`
  - [x] `Remove({ MessageID, ChannelID }): {}`

---
- [x] Runner
  - [x] `Run({ Query }): JSON`
    - **Note**: Runs arbitrary SQL queries, and returns a dynamic JSON object.

> **Note**: This is not an exhaustive list, we will find commands we will need as we go.
